apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-python-app
  labels:
    app: {{ .Release.Name }}-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-python-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-python-app
    spec:
      containers:
        - name: python-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env : 
            - name: API_VERSION
              value: {{ .Values.env.API_VERSION }}
          ports:
            - containerPort: 5000
